### ISSUE TITLE
visual studio or vsCode as a dependency

### ISSUE THREAD

**Issue by tyrng** [zhuoyang/TARUCTimeTable-to-CSV#1]
`ModuleNotFoundError: No module named 'ptvsd'`
Above error is shown when execute directly without using any IDE. After some research I found that ptvsd is a Python debugger package for visual studio / vsCode. 

I think the 'release' version of the script should not contain this code?

**Comment by zhuoyang** [comment]
Yeah agree, it is dependency for the commented code used for debugging, 
fixed in f7a50f8d25d8f538b616398436e1a443104d4839
